### PR TITLE
added new screenshots

### PR DESCRIPTION
**Pull request by orestesgaolin**
Sumatra PDF 3.2.1

### CODE REVIEW

**Comment by kjk** [comment]
Thanks for PR but ideally what I want for screenshots is to showcase different states (start page, pdf view, comic book view, ebook view) in a lightbox style presentation. Replacing one view for another is a half measure.

**Comment by orestesgaolin** [comment]
Thanks for the info, perhaps [something like this](https://perfundo.oberlehner.net/) would be suitable?

**Comment by kjk** [comment]
That's the general idea (although this particular implementation is a bit aggressive in blocking the rest of the page; at the very least a click outside should dismiss the overlay).

Somethings as simple as https://dbheroapp.com/gui-database-client-for-mysql-postgresql-mac-osx would work.

**Comment by orestesgaolin** [comment]
Yes, that's a neat way to showcase the GUI. I don't promise, but maybe I can help :)

**Pull request closed without merging**
